env: flex
runtime: nodejs
env_variables:
  NODE_ENV: production
  SQL_USER: reis
  SQL_PASSWORD: sever0s
  SQL_DATABASE: postgres
  INSTANCE_CONNECTION_NAME: boguosgnomon:europe-west3:gnomon
beta_settings:
  cloud_sql_instances: boguosgnomon:europe-west3:gnomon
